### ISSUE TITLE
need realease bundle in github repo

### ISSUE THREAD

**Issue by chenjiajia** [googlecodelabs/codelab-elements#47] opened 2018-08-14 07:52 UTC
I installed bazel and spent a day compiling this project.
First win10 prompts various header files missing,after fix it, then bazel prompt class is missing because of  bazel default jdk9 , replaced with low version bazel there are other problems, finally  i user 1C1G ubuntu vps compile, after a free minutes, pompt  the memory is not enough, although it is bazel problem , but i hope you  to provide compiled bundle  , so it is much simpler to use.
thanks

**Comment by x1ddos** [comment] 2018-09-11 20:17
This is a duplicate of https://github.com/googlecodelabs/codelab-elements/issues/6.

**Closed by x1ddos** 2018-09-11 20:17 UTC
